from collections.abc import Callable, Mapping
from typing import Any, Iterable, TypeVar

from ..utils.types import (
    Adapter,
    AdapterRegistry,
    ArgsRegistry,
    DictType,
    ListType,
    ModuleRegistry,
    TypeType,
)

# ---------- Public API ----------

__all__: ListType[str]

_T = TypeVar("_T")

_lazy_modules: ModuleRegistry
_ADAPTERS: AdapterRegistry
_CONSTRUCTOR_DEFAULTS: ArgsRegistry[Any]
_LAZY_LIBRARY_HANDLERS: DictType[str, Callable[[], None]]


# ---------- Adapters registry ----------
def fqname_for_cls(cls: TypeType[Any]) -> str: ...
def register_adapter(cls: TypeType[Any], func: Adapter) -> Any: ...
def unregister_adapter(cls: TypeType[Any]) -> None: ...
def get_adapter_registry() -> AdapterRegistry: ...

def _get_adapter_for_type(t: TypeType[Any]) -> Adapter | None: ...
def get_adapter(x: Any) -> Adapter | None: ...


# ---------- Lazy Library Initialization Logic ----------
def _register_numpy_adapters() -> None: ...
def _register_pandas_adapters() -> None: ...
def _register_torch_adapters() -> None: ...
def _register_xarray_adapters() -> None: ...
def _ensure_library_adapters(obj: Any) -> None: ...


# ---------- Safe constructors ----------
def register_constructor_defaults(cls: TypeType[Any], /, **defaults: Any) -> None: ...
def unregister_constructor_defaults(cls: TypeType[Any]) -> None: ...
def get_defaults_registry() -> ArgsRegistry[Any]: ...

def construct_from_iterable(cls: TypeType[_T], iterable: Iterable[Any]) -> Any: ...
def construct_from_mapping(cls: TypeType[_T], items: Mapping[Any, Any]) -> Any: ...


# ---------- Lazy adapter registration ----------
def _maybe_register_builtin_adapters() -> None: ...


# ---------- Plugin discovery ----------
def discover_and_register_plugins(package_name: str) -> ListType[str]: ...
