from __future__ import annotations
from abc import abstractmethod
from collections.abc import (
    Callable, Generator, ItemsView, Iterable, Iterator, Mapping,
    KeysView, MutableMapping, ValuesView
)
from contextlib import contextmanager
from typing import (
    Any, Generic, Optional, Protocol, SupportsIndex, TypeVar, Union,
    overload
)
from typing_extensions import Self


from .._core import abstract
from .._core.base import LattixNode
from .._core.mixins import ThreadingMixin, LogicalMixin, FormatterMixin

from ..serialization import safe_yaml

from ..utils import common, exceptions
from ..utils.types import (
   JOIN_METHOD, MERGE_METHOD,
   ClassAttrSet, DictType, ListType, TupleType, SetType, 
)


_S = TypeVar("_S")
_T = TypeVar("_T")
_T1 = TypeVar("_T1")
_T2 = TypeVar("_T2")
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
_VT_co = TypeVar("_VT_co", covariant=True)


# -----------------------
# Protocols
# -----------------------
class SupportsKeysAndGetItem(Protocol[_KT, _VT_co]):
    def keys(self) -> Iterable[_KT]: ...
    def __getitem__(self, __key: _KT) -> _VT_co: ...



# -----------------------
# Main
# -----------------------
class Lattix(
    MutableMapping[_KT, _VT], Generic[_KT, _VT], LattixNode, 
    ThreadingMixin, LogicalMixin, FormatterMixin
):
   __INTERNAL_ATTRS__: ClassAttrSet
   __CLASS_ATTRS__: ClassAttrSet
   
   # ========== Constructors & Classmethods ==========
   @overload
   def __init__(self, data: None = None, *, 
                key: str = "", parent: Lattix[_KT, _VT] | None = None, 
                sep: str = ..., lazy_create: bool = ..., 
                ts_level: int = 0, **kwargs: Any) -> None: ...
   @overload
   def __init__(self, data: Mapping[_KT, _VT], *, 
                key: str = "", parent: Lattix[_KT, _VT] | None = None, 
                sep: str = ..., lazy_create: bool = ..., 
                ts_level: int = 0, **kwargs: Any) -> None: ...
   @overload
   def __init__(self, data: Iterable[TupleType[_KT, _VT]], *, 
                key: str = "", parent: Lattix[_KT, _VT] | None = None, 
                sep: str = ..., lazy_create: bool = ..., 
                ts_level: int = 0, **kwargs: Any) -> None: ...
   @overload
   def __init__(self, data: Any, *, 
                key: str = "", parent: Lattix[_KT, _VT] | None = None, 
                sep: str = ..., lazy_create: bool = ..., 
                ts_level: int = 0, **kwargs: Any) -> None: ...
   def __new__(cls, *args: Any, **kwargs: Any) -> Self: ...
   def __getstate__(self) -> DictType[str, str | int | DictType[_KT, _VT] | None]: ...
   def __setstate__(self, state: TupleType[DictType[_KT, _VT], bool, int | None]) -> None: ...
   def __reduce__(self) -> TupleType[Lattix[_KT, _VT], TupleType[DictType]]: ...
   def __reduce_ex__(self, protocol: SupportsIndex, /) -> TupleType[Lattix[_KT, _VT], TupleType[DictType]]: ...
   @classmethod
   def __class_getitem__(cls, item: Any) -> Lattix[Any, Any]: ...

   @classmethod
   @overload
   def fromkeys(cls, iterable: Iterable[_T], value: None = None, /) -> Lattix[_T, Any | None]: ...
   @classmethod
   @overload
   def fromkeys(cls, iterable: Iterable[_T], value: _S, /) -> Lattix[_T, _S]: ...
   @classmethod
   def fromkeys(cls, iterable: Iterable[_T], value: Any = None, /) -> Lattix[_T, Any]: ...

   @classmethod
   def from_dict(cls, d: DictType[_KT, _VT], sep: str = ...) -> Lattix[_KT, Any]: ...
   @classmethod
   def from_json(cls, data: str | bytes, encoding: str = ..., *, from_file: bool = ...) -> Lattix[_KT, _VT]: ...
   @classmethod
   def from_yaml(cls, data: str | bytes, encoding: str = ..., *, from_file: bool = ..., enhanced: bool = ...,) -> Lattix[_KT, _VT]: ...

   # ========== Properties ==========
   @property
   def sep(self) -> str: ...
   @sep.setter
   def sep(self, symbol: str) -> None: ...

   @property
   def lazy_create(self) -> bool: ...
   @lazy_create.setter
   def lazy_create(self, lazy_create: bool) -> None: ...

   @property
   def ts_level(self) -> int: ...
   @ts_level.setter
   def ts_level(self, level: int) -> None: ...

   # ========== Internal helpers ==========
   def _walk_path(self, path: str, stop_before_last: bool = ...) -> TupleType[Lattix[_KT, _VT], _KT] | Any: ...
   def _wrap_value(self, value: Any) -> Any: ...
   @contextmanager
   def _context_lock(self, level: Any | None = None) -> Generator[None, Any, None]: ...

   # ========== MutableMapping core (Mapping protocol / Basic dict-like) ==========
   def __getitem__(self, key: _KT) -> _VT | Lattix[_KT, _VT]: ...
   def __setitem__(self, key: _KT, value: _VT) -> None:...
   def __delitem__(self, key: _KT) -> None: ...
   def __iter__(self) -> Iterator[_KT]: ...
   def __len__(self) -> int: ...
   def __contains__(self, key: _KT) -> bool: ...
   def __reversed__(self) -> Iterator[_KT]: ...
   def __eq__(self, other: object) -> bool: ...
   def keys(self) -> KeysView[_KT]: ...
   def values(self) -> ValuesView[_VT]: ...
   def items(self) -> ItemsView[_KT, _VT]: ...

   @overload
   def get(self, key: _KT, default: None = None, /) -> Optional[_VT]: ...
   @overload
   def get(self, key: _KT, default: _VT, /) -> _VT: ...
   @overload
   def get(self, key: _KT, default: _T, /) -> Union[_VT, _T]: ...
   def get(self, key: _KT, default: Any = None, /) -> Any: ...

   @overload
   def setdefault(self, key: _KT, default: None = None, /) -> Optional[_VT]: ...
   @overload
   def setdefault(self, key: _KT, default: _T, /) -> Union[_VT, _T]: ...
   def setdefault(self, key: _KT, default: Any = None, /) -> Any: ...

   @overload
   def pop(self, key: _KT, /) -> _VT: ...
   @overload
   def pop(self, key: _KT, default: _VT, /) -> _VT: ...
   @overload
   def pop(self, key: _KT, default: _T, /) -> Union[_VT, _T]: ...
   def pop(self, key: _KT, default: Any = None, /) -> Any: ...

   def popitem(self) -> TupleType[_KT, _VT]: ...
   def clear(self) -> None: ...

   @overload
   def update(self, **kwargs: _VT) -> None: ...
   @overload
   def update(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> None: ...
   @overload
   def update(self, other: Iterable[TupleType[_KT, _VT]], /) -> None: ...
   def update(self, *args: Any, **kwargs: _VT) -> None: ...

   def copy(self) -> Lattix[_KT, _VT]: ...

   # ========== Attribute-style access ==========
   def __getattr__(self, name: str) -> _VT | Lattix: ...
   def __setattr__(self, name: str, value: _VT) -> None: ...
   def __delattr__(self, name: str) -> None: ...
   def __dir__(self) -> ListType[str]: ...
   
   # ========== Comparison & Representation ==========
   def __repr__(self) -> str: ...
   def __str__(self) -> str: ...
   def pprint(self, indent: int = 0) -> str: ...
   def __format__(self, format_spec: str) -> str: ...
   def __pertty__(self, printer: Any, cycle: Any) -> None: ...

   # ========== Merge / Logical operators ==========
   # --- add (+) ---
   @overload
   def __add__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __add__(self, other: Lattix[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __add__(self, other: Any, /) -> Lattix[_KT, _VT]: ...

   @overload
   def __iadd__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __iadd__(self, other: Lattix[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __iadd__(self, other: Any, /) -> Lattix[_KT, _VT]: ...
   
   @overload
   def merge(self, other: DictType[_KT, _VT], overwrite: bool = True, /) -> Lattix[_KT, _VT]: ...
   @overload
   def merge(self, other: Lattix[_KT, _VT], overwrite: bool = True, /) -> Lattix[_KT, _VT]: ...
   @overload
   def merge(self, other: Mapping[_KT, _VT], overwrite: bool = True, /) -> Lattix[_KT, _VT]: ...
   def merge(self, other: Any, overwrite: bool = True, /) -> Lattix[_KT, _VT]: ...

   # --- and (&) ---
   @overload
   def __and__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __and__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   @overload
   def __and__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __and__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __and__(self, other: Any, /) -> Lattix[Any, Any]: ...
   
   @overload
   def __rand__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __rand__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   def __rand__(self, other: Any, /) -> Lattix[Any, Any]: ...
   
   @overload
   def __iand__(self, other: DictType[_KT, _VT], /) -> Self: ...
   @overload
   def __iand__(self, other: Lattix[_T1, _T2], /) -> Self: ...
   @overload
   def __iand__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Self: ...
   @overload
   def __iand__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Self: ...
   def __iand__(self, other: Any, /) -> Self: ...

   def _and_impl(self, other, inplace: bool = ...) -> Lattix: ...
   def and_(self, other, inplace: bool = ...): ...

   # --- or (|) ---
   @overload
   def __or__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __or__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   @overload
   def __or__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __or__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __or__(self, other: Any, /) -> Lattix[Any, Any]: ...

   @overload
   def __ror__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __ror__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   def __ror__(self, other: Any, /) -> Lattix[Any, Any]: ...
   
   @overload
   def __ior__(self, other: DictType[_KT, _VT], /) -> Self: ...
   @overload
   def __ior__(self, other: Lattix[_T1, _T2], /) -> Self: ...
   @overload
   def __ior__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Self: ...
   @overload
   def __ior__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Self: ...
   def __ior__(self, other: Any, /) -> Self: ...

   def _or_impl(self, other, inplace: bool = ...) -> Lattix: ...
   def or_(self, other, inplace: bool = ...): ...

   # --- sub (-) ---
   @overload
   def __sub__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __sub__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   @overload
   def __sub__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __sub__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __sub__(self, other: Any, /) -> Lattix[Any, Any]: ...

   @overload
   def __rsub__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __rsub__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   def __rsub__(self, other: Any, /) -> Lattix[Any, Any]: ...
   
   @overload
   def __isub__(self, other: DictType[_KT, _VT], /) -> Self: ...
   @overload
   def __isub__(self, other: Lattix[_T1, _T2], /) -> Self: ...
   @overload
   def __isub__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Self: ...
   @overload
   def __isub__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Self: ...
   def __isub__(self, other: Any, /) -> Self: ...

   def _sub_impl(self, other, inplace: bool = ...) -> Lattix: ...
   def sub(self, other, inplace: bool = ...): ...

   # --- xor (^) ---
   @overload
   def __xor__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __xor__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   @overload
   def __xor__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __xor__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   def __xor__(self, other: Any, /) -> Lattix[Any, Any]: ...

   @overload
   def __rxor__(self, other: DictType[_KT, _VT], /) -> Lattix[_KT, _VT]: ...
   @overload
   def __rxor__(self, other: Lattix[_T1, _T2], /) -> Lattix[_KT | _T1, _VT | _T2]: ...
   def __rxor__(self, other: Any, /) -> Lattix[Any, Any]: ...
   
   @overload
   def __ixor__(self, other: DictType[_KT, _VT], /) -> Self: ...
   @overload
   def __ixor__(self, other: Lattix[_T1, _T2], /) -> Self: ...
   @overload
   def __ixor__(self, other: Iterable[TupleType[_KT, _VT]], /) -> Self: ...
   @overload
   def __ixor__(self, other: SupportsKeysAndGetItem[_KT, _VT], /) -> Self: ...
   def __ixor__(self, other: Any, /) -> Self: ...

   def _xor_impl(self, other: Any, inplace: bool = ...) -> Lattix: ...
   def xor(self, other: Any, inplace: bool = ...): ...

   # --- join ---
   def join(self, other: Any, how: JOIN_METHOD = "inner", merge: MERGE_METHOD = "tuple") -> Lattix[_KT, _VT]: ...
   
   # ========== Leaf / Traversal utilities ==========
   def leaf_keys(self) -> Iterator[str]: ...
   def leaf_values(self) -> Iterator[_VT]: ...
   def map_leaves(self, func: Callable[[_VT], _VT]) -> None: ...
   def filter_leaves(self, func: Callable[[_VT], bool]) -> None: ...
   def walk(self, path: tuple = ()) -> Generator[tuple | Any, Any, None]: ...
   def get_path(self, path: str, default: Any = None) -> Any: ...
   def has_path(self, path: str) -> bool: ...
   def is_leaf(self, path: str) -> bool: ...
   def to_records(self) -> ListType: ...
   
   # ========== Serialization & Export ==========
   def to_dict(self) -> DictType: ...
   def to_list(self) -> ListType: ...
   def to_tuple(self) -> TupleType: ...
   def to_json(self, **kwargs: _VT) -> str: ...
   def to_yaml(self, enhanced: bool = ..., **kwargs: _VT) -> str: ...
   def __deep_convert__(self, value: Any, ftype: type = DictType, **kwargs: Any) -> Any: ...
   def deep_convert(self, ftype: type = DictType, **kwargs: Any) -> Any: ...
   def _to_serializable(self, obj: Any, _seen: SetType) -> Any: ...

   # ========== Copy & Sort utilities ==========
   def __deepcopy__(self, memo) -> Lattix[_KT, _VT]: ...
   def clone(self, deep: bool = True, keep_state: bool = True) -> Lattix[_KT, _VT]: ...
   def sort_by_key(self, reverse: bool = ..., recursive: bool = ...) -> Self: ...
   def sort_by_value(self, reverse: bool = ..., recursive: bool = ...) -> Self: ...

   # ========== Lifecycle & Cleanup ==========
   def detach(self, clear_locks: bool = ...) -> None: ...
   def attach(self, parent: Lattix[_KT, _VT], propagate: bool = True) -> Self: ...
   def __del__(self) -> None: ...

class SlimmedLattix(Lattix[_KT, _VT]):
   def __getattr__(self, name: str) -> _VT: ...
   def __setattr__(self, name: str, value: _VT) -> None: ...
