from __future__ import annotations
from _thread import RLock as RLockType
from collections.abc import (
    ItemsView, Iterable, Iterator, Mapping, KeysView, MutableMapping, 
    ValuesView
)
from typing import (
    Any, Generic, Protocol, SupportsIndex, TypeVar, overload
)
from typing_extensions import Self


from .._core.base import LattixNode
from .._core.mixins import ThreadingMixin, LogicalMixin, FormatterMixin


from ..utils.types import (
   JOIN_METHOD, MERGE_METHOD,
   ClassAttrSet, DictType, ListType, SetType, TupleType, TypeType
)


_T = TypeVar("_T")
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
_VT_co = TypeVar("_VT_co", covariant=True)


# -----------------------
# Protocols
# -----------------------
class SupportsKeysAndGetItem(Protocol[_KT, _VT_co]):
    def keys(self) -> Iterable[_KT]: ...
    def __getitem__(self, __key: _KT) -> _VT_co: ...


# -----------------------
# Main
# -----------------------
class Lattix(
    MutableMapping[_KT, _VT], Generic[_KT, _VT], LattixNode, 
    ThreadingMixin, LogicalMixin, FormatterMixin
):
    __INTERNAL_ATTRS__: ClassAttrSet
    __CLASS_ATTRS__: ClassAttrSet
    
    # ========== Constructors & Classmethods ==========
    def __init__(
        self,
        data: Any = None,
        *,
        key: str = "",
        parent: Any = None,
        sep: str = "/",
        lazy_create: bool = False,
        enable_lock: bool = False,
        **kwargs: Any
    ) -> None: ...

    def __new__(cls, *args: Any, **kwargs: Any) -> Self: ...

    def _config(self) -> TupleType[str, bool, bool]: ...

    @classmethod
    def _construct(
        cls, 
        mapping: Any, 
        config: TupleType[str, Any, str, bool, bool] = ..., 
        /, 
        **kwargs: Any
    ) -> Self: ...
    
    def __getstate__(self) -> DictType[str, Any]: ...
    def __setstate__(self, state: DictType[str, Any]) -> None: ...
    def __reduce__(self) -> TupleType[TypeType[Self], TupleType[()], DictType[str, Any]]: ...
    def __reduce_ex__(self, protocol: SupportsIndex, /) -> TupleType[Lattix[_KT, _VT], TupleType[DictType]]: ...

    @classmethod
    def __class_getitem__(cls, item: Any) -> Any: ...

    # ========== Factories ==========
    @classmethod
    def fromkeys(cls, iterable: Iterable[_KT], value: Any = None) -> Self: ...

    @classmethod
    def from_dict(cls, d: DictType[_KT, _VT], sep: str = ...) -> Self: ...

    @classmethod
    def from_json(cls, data: str | bytes, encoding: str = ..., *, from_file: bool = ...) -> Self: ...

    @classmethod
    def from_orjson(cls, data: str | bytes) -> Self: ...

    @classmethod
    def from_msgpack(cls, data: str | bytes) -> Self: ...

    @classmethod
    def from_yaml(cls, data: str | bytes, encoding: str = ..., *, from_file: bool = ..., enhanced: bool = ...,) -> Self: ...

    @classmethod
    def _get_class_attrs(cls) -> ClassAttrSet: ...

    # ========== Properties ==========
    @property
    def sep(self) -> str: ...
    @sep.setter
    def sep(self, symbol: str) -> None: ...

    @property
    def lazy_create(self) -> bool: ...
    @lazy_create.setter
    def lazy_create(self, value: bool) -> None: ...

    # ========== Internal helpers ==========
    def _promote_child(self, key: str, value: Any, parent_node: Any) -> Lattix[_KT, _VT]: ...

    def _walk_path(self, path: str = ..., stop_before_last: bool = ..., force_no_create: bool = ...) -> TupleType[Lattix[_KT, _VT], _KT] | Any: ...

    @staticmethod
    def _convert_iterable(node: Lattix[_KT, _VT], key: str, iterable: Iterable[Any]) -> Any: ...

    # ========== MutableMapping core (Mapping protocol / Basic dict-like) ==========
    def __getitem__(self, key: _KT | str) -> Any: ...
    def __setitem__(self, key: _KT | str, value: _VT | Any) -> None:...
    def __delitem__(self, key: _KT | str) -> None: ...
    def __iter__(self) -> Iterator[_KT]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __reversed__(self) -> Iterator[_KT]: ...
    def __eq__(self, other: object) -> bool: ...

    # Standard dict methods
    def keys(self) -> KeysView[_KT]: ...
    def values(self) -> ValuesView[_VT]: ...
    def items(self) -> ItemsView[_KT, _VT]: ...

    @overload
    def get(self, key: _KT, default: None = None, /) -> Any | None: ...
    @overload
    def get(self, key: _KT, default: _T, /) -> Any | _T: ...

    def setdefault(self, key: _KT, default: Any = None, /) -> Any: ...

    @overload
    def pop(self, key: _KT) -> Any: ...
    @overload
    def pop(self, key: _KT, default: _T, /) -> Any | _T: ...

    def popitem(self) -> TupleType[_KT, _VT]: ...
    def clear(self) -> None: ...

    def update(
        self,
        other: SupportsKeysAndGetItem[_KT, _VT] | Iterable[TupleType[_KT, _VT]] = ...,
        **kwargs: Any
    ) -> None: ...

    def copy(self) -> Self: ...

    # ========== Attribute-style access ==========
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __dir__(self) -> ListType[str]: ...
    
    # ========== Comparison & Representation ==========
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def _repr_pretty_(self, printer: Any, cycle: Any) -> None: ...
    def __pretty__(self, printer: Any, cycle: bool) -> None: ...
    def pprint(self, indent: int = 0) -> str: ...

    # ========== Merge / Logical operators ==========
    # --- add (+) ---
    def __add__(self, other: Any) -> Self: ...
    def __iadd__(self, other: Any) -> Self: ...
    
    def merge(
        self, 
        other: Mapping[_KT, _VT], 
        overwrite: bool = ...
    ) -> Self: ...

    # --- and (&) / intersection ---
    def _set_operation(
        self,
        other: Mapping[_KT, _VT] | Any,
        op: str,
        inplace: bool = ...
    ) -> Self: ...

    def _and_impl(self, other: Any, inplace: bool = ...) -> Self: ...

    # --- or (|) / union ---
    def _or_impl(self, other: Any, inplace: bool = ...) -> Self: ...

    # --- sub (-) / difference ---
    def _sub_impl(self, other: Any, inplace: bool = ...) -> Self: ...

    # --- xor (^) / symmetric difference ---
    def _xor_impl(self, other: Any, inplace: bool = ...) -> Self: ...

    # --- join ---
    def join(
        self, 
        other: Any, 
        how: JOIN_METHOD = ..., 
        merge: MERGE_METHOD = ...
    ) -> Self: ...
    
    # ========== Leaf / Traversal utilities ==========
    def get_path(self, path: str = ..., default: Any = None) -> Any: ...
    def has_path(self, path: str = ...) -> bool: ...
    def is_leaf(self, path: str = ...) -> bool: ...
    
    # ========== Serialization & Export ==========
    def to_dict(self) -> DictType[_KT, _VT]: ...
    def to_list(self) -> ListType[TupleType[_KT, _VT]]: ...
    def to_tuple(self) -> TupleType[TupleType[_KT, _VT]]: ...
    def json(self, **kwargs: Any) -> str: ...
    def orjson(self, **kwargs: Any) -> bytes: ...
    def msgpack(self) -> Any | None: ...
    def yaml(self, enhanced: bool = ..., **kwargs: Any) -> str: ...

    # ========== Copy & Sort utilities ==========
    def __deepcopy__(self, memo: DictType[int, Any]) -> Self: ...

    def clone(
        self, 
        deep: bool = ..., 
        keep_state: bool = ...,
        share_lock: bool = ...,
        memo: DictType[int, Any] | None = ...
    ) -> Self: ...

    def sort_by_key(self, reverse: bool = ..., recursive: bool = ...) -> Self: ...
    def sort_by_value(self, reverse: bool = ..., recursive: bool = ...) -> Self: ...

    # ========== Lifecycle & Cleanup ==========
    @staticmethod
    def _propagate_attrs(
        obj: Any,
        attrs: DictType[str, Any] = ...,
        seen: SetType[int] | None = ...
    ) -> None: ...

    @staticmethod
    def _propagate_lock(
        obj: Any, 
        enable_lock: bool,
        lock: RLockType | None, 
        seen: SetType[int] | None = ...
    ) -> None: ...

    def freeze(self) -> None: ...
    def unfreeze(self) -> None: ...
    def detach(self, clear_locks: bool = ...) -> None: ...
    def attach(self, parent: Any) -> None: ...
    def transplant(self, parent: Any, key: _KT | None = ...) -> None: ...
    def __del__(self) -> None: ...
