from __future__ import annotations
from collections.abc import Callable, Iterable, ItemsView, KeysView, ValuesView
from typing import Any, Literal
from typing_extensions import Self
from weakref import ReferenceType


from ..utils.types import DictType, ListType, SetType, TupleType, TRAV_ORDER


class LattixNode:
    _parent: ReferenceType[LattixNode] | None
    _children: DictType[str, Any]
    _key: str

    def __init__(self, key: str = ..., parent: Any = None) -> None: ...

    # Parent / Children Properties
    @property
    def key(self) -> str: ...
    
    @property
    def parent(self) -> LattixNode | None: ...
    
    @parent.setter
    def parent(self, value: LattixNode | None) -> None: ...

    @property
    def children(self) -> DictType[str, Any]: ...

    # Dict-like API
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def items(self) -> ItemsView[str, Any]: ...
    def empty(self) -> bool: ...

    # Hierarchy operations
    def detach(self) -> Self: ...
    def attach(self, parent: Any) -> Self: ...
    def transplant(self, parent: Any, key: str = ...) -> Self: ...

    # Validation
    @staticmethod
    def _validate_parent_node(parent: Any) -> Literal[True]: ...
    
    @staticmethod
    def _validate_attachable_node(obj: Any, parent: Any) -> Literal[True]: ...

    # Ancestors / Tree utils
    def is_root(self) -> bool: ...
    def get_parent(self) -> LattixNode | None: ...
    def _ancestors(self) -> Iterable[LattixNode]: ...
    def get_root(self) -> LattixNode: ...
    def is_cycled(self) -> bool: ...

    # Walk / Traverse
    def walk(self, path: TupleType[Any, ...] = ...) -> Iterable[tuple[tuple[str, ...], Any]]: ...

    def traverse(self, order: TRAV_ORDER = ..., _seen: SetType[int] | None = None) -> Iterable[LattixNode]: ...

    # Leaf Utilities
    def leaf_keys(self) -> Iterable[str]: ...
    def leaf_values(self) -> Iterable[Any]: ...
    def map_leaves(self, func: Callable[..., Any]) -> None: ...
    def filter_leaves(self, func: Callable[..., bool]) -> None: ...

    # Flatten records
    def to_records(self) -> ListType[TupleType[str, Any]]: ...

    # Representation
    def __repr__(self) -> str: ...
